import * as vscode from "vscode";
import type { CockpitStrings } from "./shared/control/messages.js";

export function cockpitStrings(): CockpitStrings {
  const t = vscode.l10n.t;
  return {
    title: t("Control"),
    subtitle: t("Project sysadmin"),
    navOverview: t("Overview"),
    navEngine: t("Engine"),
    navFleet: t("Fleet"),
    navInbox: t("Inbox"),
    navApprovals: t("Approvals"),
    navMission: t("Board"),
    navValidations: t("Validations"),
    navHandoff: t("Handoff"),
    navWorktrees: t("Worktrees"),
    navRuntime: t("Runtime Ops"),
    navRuntimeConfig: t("Runtime Config"),
    navTmux: t("tmux"),
    navPlugins: t("Plugins"),
    navSettings: t("Settings"),
    back: t("Back"),
    refresh: t("Refresh"),
    auto: t("Auto-refresh"),
    empty: t("No Tachyon workspace attached in this window."),
    copyDiagnostics: t("Copy diagnostics"),
    openMissionControl: t("Open Board"),
    openSettings: t("Open Settings"),
    openDoctor: t("Run Doctor"),
    copied: t("Diagnostics copied"),
    overviewTitle: t("Overview"),
    overviewHint: t("Health snapshot. Fleet = agents (sidebar); Board = work queue."),
    engineTitle: t("Engine / Bridge"),
    fleetTitle: t("Fleet"),
    fleetHint: t("Agents (runtime) — start, stop, terminal, activity. Work items are on the Board."),
    approvalsTitle: t("Approvals"),
    approvalsHint: t("Human gates that block the fleet (embedded)."),
    missionTitle: t("Board"),
    missionHint: t("Work queue — tasks and lanes. Agents live in the sidebar Fleet."),
    validationsTitle: t("Validations"),
    validationsHint: t("Validation queue — close dogfoods and checks (not on the Board)."),
    navExecutionGraph: t("Execution"),
    settingsTitle: t("Settings"),
    settingsHint: t("Personal machine preferences and shared project policy — two files, two authorities."),
    workspaces: t("Workspaces"),
    engines: t("Engines"),
    agents: t("Agents"),
    errors: t("Errors"),
    bridges: t("Bridges"),
    approvals: t("Approvals"),
    inbox: t("Waiting on you"),
    worktrees: t("Worktrees"),
    attached: t("attached"),
    error: t("error"),
    none: t("none"),
    state: t("State"),
    pid: t("PID"),
    version: t("Version"),
    instance: t("Instance"),
    started: t("Started"),
    bundle: t("Bundle"),
    protocol: t("Protocol"),
    url: t("URL"),
    port: t("Port"),
    auth: t("Auth"),
    root: t("Root"),
    hash: t("Hash"),
    running: t("running"),
    stopped: t("stopped"),
    checkedAt: t("Checked"),
    navLoading: t("Loading…"),
    navStalled: t("This is taking longer than expected."),
    navRetry: t("Retry"),
    open: t("Open"),
    noneListed: t("Nothing listed for this workspace yet."),
    kind: t("Kind"),
    branch: t("Branch"),
    status: t("Status"),
    phase: t("Phase"),
    path: t("Path"),
    name: t("Name"),
    start: t("Start"),
    stop: t("Stop"),
    openTerminal: t("Terminal"),
    openActivity: t("Activity"),
    openProbes: t("Probes"),
    editAgent: t("Edit"),
    continueTask: t("Continue task in…"),
    continueTaskPickTitle: t("Continue task from {0} in…"),
    continueTaskPickSubtitle: t(
      "Starts a new session on the destination with a focused handoff — not a native resume of the source session.",
    ),
    continueTaskPickPlaceholder: t("Filter destination agents…"),
    continueTaskPickEmpty: t("No other declared agent to continue into"),
    continueTaskDestStopped: t("stopped"),
    continueTaskDestRunning: t("running — stop first"),
    continueTaskDestDetail: t("New session with focused handoff from {0}"),
    continueTaskNoDest: t("No other declared agent to continue into (need a stopped destination)."),
    reveal: t("Reveal"),
    copyPath: t("Copy path"),
    copyId: t("Copy id"),
    openConfig: t("Open workspace settings"),
    // t-7b4bb5 — two authorities, named so the dual open buttons do not look like a split mind.
    settingsBody: t(
      "Tachyon keeps two settings files on purpose: one for you on this machine, one for the project shared with the team. They own different knobs — they are not two places for the same list.",
    ),
    settingsScopeGlobalTitle: t("Global (personal)"),
    settingsScopeGlobalHint: t(
      "Your machine preferences — agent pane, git path, Activity theme. Not committed; recovery path when Control will not open.",
    ),
    settingsScopeWorkspaceTitle: t("Workspace (project)"),
    settingsScopeWorkspaceHint: t(
      "Shared project policy in tachyon.yml — agents, agent limit, memory cap, schedules, Companion, idle notify, worktree reveal. Versioned with the repo, so the whole team gets it.",
    ),
    settingsFileLabel: t("File:"),
    settingsOpenTachyon: t("Open global settings"),
    settingsOpenConfig: t("Open workspace settings"),
    settingsDoctor: t("Run Doctor"),
    settingsWritesTo: t("Writes to"),
    settingsWritesToEither: t("Writes to either — you pick below"),
    settingsWritesToNothing: t("Reads only"),
    cardTemplateTitle: t("Agent card layout"),
    cardTemplateHint: t("Choose which elements an agent card shows, and in what order."),
    cardTemplateComposer: t("Choose the elements"),
    cardTemplateBody: t("Compose a layout here, watch the real card update, then paste the YAML into tachyon.yml. Nothing is saved from this block."),
    cardTemplateYamlHint: t("Paste this under your workspace's tachyon.yml. Regions you did not change are left out, so they follow the default."),
    cardTemplateCopy: t("Copy YAML"),
    cardTemplateReset: t("Reset to default"),
    cardTemplateCriticalNote: t("shown anyway when a row is in this state"),
    cardTemplateInlineNote: t("renders inside another element"),
    // SDD 479 phase 5 — ratified fork 1 made this sentence part of the feature: without it, a
    // personal override quietly contradicting the project reads as a broken project template.
    cardTemplateInEffect: t("In effect right now:"),
    cardTemplatePersonalActive: t("your personal override in your Tachyon settings file — it wins over every project template below"),
    cardTemplatePersonalRefused: t("your personal override was REFUSED and ignored; the cards fall back to each project's template"),
    cardTemplatePersonalNone: t("no personal override — each project's own template decides"),
    cardTemplateProjectNone: t("uses Tachyon's default card"),
    cardTemplateProjectConfigured: t("has its own template in tachyon.yml"),
    cardTemplateProjectRefused: t("its tachyon.yml template was refused; showing the default card"),
    cardTemplateHomeLabel: t("Write this layout to:"),
    cardTemplateHomeProject: t("This project (tachyon.yml)"),
    cardTemplateHomePersonal: t("Just me (Tachyon settings file)"),
    cardTemplateCopyJson: t("Copy JSON"),
    cardTemplateJsonHint: t("Paste this under \"sidebar\": { \"cardTemplate\": ... } in your Tachyon settings file. It applies to every project you open, and wins over their templates; regions you did not change keep whatever each project chose."),
    cardTemplateOpenSettings: t("Open settings"),
    companionTitle: t("Companion"),
    companionHint: t("Pair Tachyon Companion and opt-in first-person browser tools for agents (user_browser_*)."),
    companionBody: t(
      "When tab tools are on, agents see user_browser_* on the Bridge. Pairing Companion is still required to run them. Generate a pair code here (or via the command palette).",
    ),
    companionTabTools: t("List Companion tab tools for agents"),
    companionTabToolsHelp: t("Writes settings.companion.tabTools in tachyon.yml and refreshes the Bridge tool list."),
    companionAllowedHosts: t("Allowed hosts (optional)"),
    companionAllowedHostsHelp: t(
      "One host or glob per line (example.com, *.herokuapp.com). Empty = all hosts. Writes settings.companion.allowedHosts in tachyon.yml.",
    ),
    companionAllowedHostsPlaceholder: t("example.com\n*.herokuapp.com"),
    // SDD 488 F4 — Integrated Browser GA gate (human surface + call-time; tools stay listed).
    ideBrowserTitle: t("Integrated Browser"),
    ideBrowserHint: t("VS Code editor browser and Design Mode. Opt in before the status-bar controls appear."),
    ideBrowserBody: t(
      "When enabled, the globe and Design Mode icons show on the status bar. Agents always see ide_browser_* tools; calls fail until you enable this and open the bridge.",
    ),
    ideBrowserEnabled: t("Enable Integrated Browser"),
    ideBrowserEnabledHelp: t("Writes settings.ideBrowser.enabled in tachyon.yml. Does not remove tools from the Bridge catalog."),
    // t-585d5c — the unit and the bounds are IN the strings, because a bare number field is where a
    // person guesses seconds and gets minutes.
    idleNotifyTitle: t("Idle agent notifications"),
    idleNotifyHelp: t(
      "How long a child agent may sit idle before Tachyon notifies its parent. 1-10080 minutes (7 days). Writes settings.agentNotifications.idleAfterMinutes in tachyon.yml and applies on the next check — no restart.",
    ),
    idleNotifyUnit: t("minutes"),
    idleNotifyUsingDefault: t("Using the default ({0} min) — nothing written in tachyon.yml"),
    idleNotifyOff: t("Notifications are off for this workspace"),
    idleNotifyOffLabel: t("Turn notifications off"),
    idleNotifySave: t("Save"),
    idleNotifyReset: t("Back to default"),
    // t-aaad95 — Control -> Settings edits BOTH scopes now that VS Code contributes nothing.
    globalSettingsTitle: t("Your Tachyon settings"),
    globalSettingsHint: t("Per-person, per-machine. Kept in a plain file you can also edit by hand — that file is the recovery path when Control itself will not open."),
    globalSettingsFileLabel: t("File:"),
    globalSettingsOpenFile: t("Open global settings"),
    globalSettingsRefused: t("This file was refused and the last good version is in use — fix it and it reloads by itself:"),
    globalSettingsCodeTheme: t("Activity code theme"),
    globalSettingsCodeThemeHelp: t("Syntax-highlight palette for code blocks in Activity."),
    globalSettingsCodeThemeAuto: t("Follow the editor"),
    globalSettingsCodeThemeDark: t("Dark"),
    globalSettingsCodeThemeLight: t("Light"),
    globalSettingsAgentPane: t("Agent pane"),
    globalSettingsAgentPaneHelp: t("The first-party agent pane. The integrated terminal stays available either way."),
    globalSettingsGitPath: t("Path to git"),
    globalSettingsGitPathHelp: t("Leave empty to use the git extension's git.path, then common install locations, then git on PATH."),
    globalSettingsSave: t("Save"),
    globalSettingsLive: t("takes effect immediately"),
    globalSettingsNeedsReopen: t("applies the next time Control is opened"),
    workspaceSettingsTitle: t("This project's settings"),
    workspaceSettingsHint: t("Agent limit, memory cap, task notifications and worktree reveal live in tachyon.yml, so they travel with the repo and the whole team gets them."),
    companionAllowedHostsSave: t("Save allowed hosts"),
    companionPaired: t("Paired"),
    companionNotPaired: t("Not paired"),
    companionPickWorkspace: t("Select a single workspace in Overview to manage Companion settings."),
    companionBaseUrl: t("Engine Base URL"),
    companionShowPairCode: t("Show pair code"),
    companionCopyBaseUrl: t("Copy URL"),
    companionPairCodeLabel: t("Code"),
    companionPairUrlLabel: t("URL"),
    companionPairExpires: t("Expires"),
    companionPairExpired: t("Code expired — generate a new one."),
    companionCopyCode: t("Copy code"),
    companionCopyUrl: t("Copy URL"),
    companionCopyAll: t("Copy all"),
    companionNewCode: t("New code"),
    companionPairUnavailable: t("Companion pairing unavailable — ensure the Bridge is listening."),
    companionPairQrLabel: t("Mobile QR"),
    companionPairQrHint: t(
      "Scan with your phone camera — opens Companion Mobile and pairs automatically. PC and phone must be on the same Tailscale tailnet (settings.companion.lanAccess: true).",
    ),
    companionPairCandidatesLabel: t("URL"),
    companionCopyPayload: t("Copy QR payload"),
    companionLanAccessHint: t(
      "Mobile uses Tailscale only (not raw Wi‑Fi IPs). Install Tailscale on PC + phone, same account/tailnet, then generate a code.",
    ),
    devicesTitle: t("Connected devices"),
    devicesHint: t("Companion devices paired to this workspace engine (browser or mobile)."),
    devicesEmpty: t("No Companion device paired. Generate a pair code above, enter it in Tachyon Companion, then refresh."),
    devicesUnpair: t("Unpair"),
    devicesLive: t("Live"),
    devicesOffline: t("Offline"),
    devicesKindBrowser: t("Browser"),
    devicesKindMobile: t("Mobile"),
    devicesPairedAt: t("Paired"),
    // SDD 482 phase 5 (`t-5e1113`) — the ratified product vocabulary; these two badges are the whole
    // user-visible surface for the distinction.
    //
    // t-4cc561 updated the claim that used to sit here. It said every OTHER occurrence of "declared"
    // or the retired species name was a frozen field/config/wire value, so the rename was two lines and not a sweep.
    // That stopped being true: the species names are now gone from identifiers, comments and copy
    // across the shell and engine. What IS still frozen, deliberately, is the narrow set that crosses
    // a boundary — the sidebar's legacy species flag, the handoff mode discriminant, and the
    // ledger's persisted shape. Those are renamed only with a protocol bump, never as nomenclature.
    saved: t("Saved"),
    temporary: t("Temporary"),
    agent: t("agent"),
    change: t("change"),
  };
}
