import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { EXTENSION_WEBVIEW_DIST } from "./support/extensionLayout.js";
import puppeteer, { type Browser, type Page } from "puppeteer-core";
import { existsSync, mkdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import path from "node:path";
import { resolveChromeExecutable } from "./support/chrome";
import { loadWebviewModule, renderStatic } from "../helpers/staticPreact.js";
import { sidebarFixtures } from "../../scripts/webview-preview/fixtures/sidebar";
import type { AgentVM, FleetVM } from "@tachyon/shared/sidebar/types.js";

/**
 * t-281339 — durable visual evidence + the 360 clip proof.
 *
 * Anchor (written before the line existed): four agents, one glance. An
 * in-progress step is the line; next pending when nothing is in-progress;
 * all-completed and no-channel occupy no line; absent is a discrete
 * --ds-warn mark. Long step text is one line; the card does not grow.
 *
 *     npm run build && npx vitest run --config vitest.browser.config.ts test/browser/sidebarPlanLineShots.test.ts
 */
const OUT_DIR = path.resolve(__dirname, "../../.tachyon/visual-qa/t-281339");
const DIST = EXTENSION_WEBVIEW_DIST;
const WIDTHS = [
  { id: "880", px: 880 },
  { id: "360", px: 360 },
] as const;

/**
 * Production sidebar order (SidebarPrototype): tokens and faces must
 * precede design-system, or gap/font/--ds-warn never resolve and the
 * shot cannot prove the operator ramp.
 */
const SIDEBAR_STYLESHEETS = [
  "codicon.css",
  "tokens.css",
  "faces.css",
  "design-system.css",
  "quick-picker.css",
  "sidebar.css",
] as const;

function rewriteLocalUrls(css: string, fromFile: string): string {
  const dir = path.dirname(fromFile);
  return css.replace(/url\((['"]?)([^'")]+)\1\)/g, (match, _q, spec: string) => {
    if (/^(data:|https?:|file:)/i.test(spec)) return match;
    const abs = path.resolve(dir, spec);
    if (!existsSync(abs)) return match;
    const ext = path.extname(abs).toLowerCase();
    const mime = ext === ".woff2" ? "font/woff2"
      : ext === ".woff" ? "font/woff"
        : ext === ".ttf" ? "font/ttf"
          : ext === ".otf" ? "font/otf"
            : "application/octet-stream";
    return `url("data:${mime};base64,${readFileSync(abs).toString("base64")}")`;
  });
}

function pageHtml(bodyHtml: string, width: number): string {
  const css = SIDEBAR_STYLESHEETS
    .map((f) => {
      const file = path.join(DIST, f);
      return `<style>${rewriteLocalUrls(readFileSync(file, "utf8"), file)}</style>`;
    })
    .join("\n");
  return `<!doctype html><html><head><meta charset="utf-8">${css}
<style>
  :root {
    --vscode-sideBar-background:#181818; --vscode-editor-background:#1f1f1f; --vscode-foreground:#cccccc;
    --vscode-font-family:system-ui,sans-serif; --vscode-font-size:13px;
    --vscode-descriptionForeground:#9d9d9d; --vscode-disabledForeground:#8a8a8a;
    --vscode-list-hoverBackground:#2a2d2e; --vscode-list-inactiveSelectionBackground:#37373d;
    --vscode-panel-border:#2b2b2b; --vscode-badge-background:#4d4d4d; --vscode-badge-foreground:#fff;
    --vscode-textCodeBlock-background:#0000004d; --vscode-button-background:#0078d4; --vscode-button-foreground:#fff;
    --vscode-charts-green:#89d185; --vscode-charts-yellow:#cca700; --vscode-charts-red:#f14c4c;
    --vscode-charts-blue:#3794ff; --vscode-charts-purple:#b180d7;
    --vscode-errorForeground:#f14c4c; --vscode-list-warningForeground:#cca700;
    --vscode-testing-iconPassed:#89d185; --vscode-terminal-ansiGreen:#89d185;
    --vscode-terminal-ansiYellow:#cca700; --vscode-terminal-ansiRed:#f14c4c;
    --vscode-widget-border:#3c3c3c; --vscode-editorWidget-border:#3c3c3c; --vscode-focusBorder:#0078d4;
  }
  body { margin:0; width:${width}px; }
  #shot { width:${width}px; }
</style></head><body><div id="shot">${bodyHtml}</div></body></html>`;
}

function fleetAgents(): AgentVM[] {
  const fixture = sidebarFixtures["internal-checklist-line"];
  const vm = fixture.vm as FleetVM;
  return vm.agents;
}

describe("t-281339 — checklist line at two widths", () => {
  let browser: Browser;
  let page: Page;
  let AgentRow: (props: unknown) => unknown;
  const written: string[] = [];

  beforeAll(async () => {
    mkdirSync(OUT_DIR, { recursive: true });
    const mod = await loadWebviewModule(path.resolve(__dirname, "../../packages/webview-ui/src/webview/sidebar/App.tsx"));
    AgentRow = mod.AgentRow as typeof AgentRow;
    browser = await puppeteer.launch({ executablePath: resolveChromeExecutable(), headless: true });
    page = await browser.newPage();
  }, 60_000);

  afterAll(async () => {
    await browser?.close();
    if (written.length) {
      writeFileSync(
        path.join(OUT_DIR, "README.md"),
        `# t-281339 — sidebar checklist line\n\nFour agents, two widths. Regenerated by \`test/browser/sidebarChecklistLineShots.test.ts\`.\n\n${written.map((f) => `- \`${f}\``).join("\n")}\n`,
        "utf8",
      );
    }
  });

  function rowsHtml(): string {
    return fleetAgents().map((a) => renderStatic(AgentRow({ a, flash: false }))).join("");
  }

  it("clips a long step at 360 and does not grow the card; shots both widths", async () => {
    for (const w of WIDTHS) {
      await page.setViewport({ width: w.px + 40, height: 900, deviceScaleFactor: 2 });
      await page.setContent(pageHtml(rowsHtml(), w.px), { waitUntil: "load" });
      const file = path.join(OUT_DIR, `internal-checklist-line-${w.id}.png`);
      const target = await page.$("#shot");
      await target!.screenshot({ path: file as `${string}.png` });
      expect(statSync(file).size, `${file} is empty`).toBeGreaterThan(1000);
      written.push(path.basename(file));

      await page.evaluate(() => document.fonts.ready);
      const measure = await page.evaluate(() => {
        const shot = document.getElementById("shot")!;
        const rows = [...shot.querySelectorAll(".row")].map((row) => ({
          name: (row as HTMLElement).dataset.name,
          width: (row as HTMLElement).getBoundingClientRect().width,
          overflow: (row as HTMLElement).scrollWidth - (row as HTMLElement).clientWidth,
        }));
        const step = shot.querySelector('[data-checklist="step"] .checklist-text') as HTMLElement | null;
        const mark = shot.querySelector('[data-checklist="absent"] .checklist-mark') as HTMLElement | null;
        const focus = shot.querySelector(".row-focus") as HTMLElement | null;
        const paintedEnum = [...shot.querySelectorAll(".checklist-mark, .checklist-text")]
          .some((el) => (el.textContent ?? "").includes("absent") || (el.textContent ?? "").includes("no-channel"));
        const warnToken = getComputedStyle(document.documentElement).getPropertyValue("--ds-warn").trim();
        const label2 = getComputedStyle(document.documentElement).getPropertyValue("--ds-operator-label2").trim();
        return {
          shotWidth: shot.getBoundingClientRect().width,
          rows,
          bodyFont: getComputedStyle(document.body).fontFamily,
          focusGap: focus ? getComputedStyle(focus).gap : null,
          step: step ? {
            text: step.textContent,
            overflow: step.scrollWidth - step.clientWidth,
            nowrap: getComputedStyle(step).whiteSpace,
            fontSize: getComputedStyle(step).fontSize,
          } : null,
          mark: mark ? {
            text: mark.textContent,
            color: getComputedStyle(mark).color,
            fontSize: getComputedStyle(mark).fontSize,
          } : null,
          warnToken,
          label2,
          paintedEnum,
        };
      });

      expect(measure.paintedEnum).toBe(false);
      expect(measure.mark?.text).toBe("No checklist");
      expect(measure.step).not.toBeNull();
      // Tokens resolved: a missing tokens.css leaves these empty and the
      // first shots looked serif with TASKt-id glued together.
      expect(measure.warnToken.length).toBeGreaterThan(0);
      expect(measure.label2.length).toBeGreaterThan(0);
      expect(measure.bodyFont).toMatch(/Tachyon|JetBrains|monospace/i);
      expect(measure.bodyFont.toLowerCase()).not.toContain("times");
      expect(measure.focusGap).not.toBe("0px");
      expect(measure.focusGap).not.toBe("normal");
      expect(measure.mark?.color).toBe("rgb(204, 167, 0)");
      expect(measure.step!.fontSize).toBe("11px");
      if (w.px === 360) {
        expect(measure.shotWidth).toBeLessThanOrEqual(360);
        expect(measure.rows.every((row) => row.width <= 360)).toBe(true);
        expect(measure.step!.nowrap).toBe("nowrap");
        expect(measure.step!.overflow).toBeGreaterThan(0);
      }
    }
  }, 60_000);
});
