import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { EXTENSION_WEBVIEW_DIST } from "./support/extensionLayout.js";
import puppeteer, { type Browser, type Page } from "puppeteer-core";
import { mkdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import path from "node:path";
import { resolveChromeExecutable } from "./support/chrome";
import { loadWebviewModule, renderStatic } from "../helpers/staticPreact.js";
import { sidebarFixtures } from "../../scripts/webview-preview/fixtures/sidebar";
import type { AgentVM, FleetVM } from "@tachyon/shared/sidebar/types.js";

/**
 * t-281339 — durable visual evidence + the 360 clip proof.
 *
 * Anchor (written before the line existed): four agents, one glance. An
 * in-progress step is the line; next pending when nothing is in-progress;
 * all-completed and sem-canal occupy no line; sem-plano is a discrete
 * --ds-warn mark. Long step text is one line; the card does not grow.
 *
 *     npm run build && npx vitest run --config vitest.browser.config.ts test/browser/sidebarPlanLineShots.test.ts
 */
const OUT_DIR = path.resolve(__dirname, "../../.tachyon/visual-qa/t-281339");
const DIST = EXTENSION_WEBVIEW_DIST;
const WIDTHS = [
  { id: "880", px: 880 },
  { id: "360", px: 360 },
] as const;

function pageHtml(bodyHtml: string, width: number): string {
  const css = ["codicon.css", "design-system.css", "sidebar.css"]
    .map((f) => `<style>${readFileSync(path.join(DIST, f), "utf8")}</style>`)
    .join("\n");
  return `<!doctype html><html><head><meta charset="utf-8">${css}
<style>
  :root {
    --vscode-sideBar-background:#181818; --vscode-editor-background:#1f1f1f; --vscode-foreground:#cccccc;
    --vscode-font-family:system-ui,sans-serif; --vscode-font-size:13px;
    --vscode-descriptionForeground:#9d9d9d; --vscode-disabledForeground:#8a8a8a;
    --vscode-list-hoverBackground:#2a2d2e; --vscode-list-inactiveSelectionBackground:#37373d;
    --vscode-panel-border:#2b2b2b; --vscode-badge-background:#4d4d4d; --vscode-badge-foreground:#fff;
    --vscode-charts-green:#89d185; --vscode-charts-yellow:#cca700; --vscode-charts-red:#f14c4c;
    --vscode-charts-blue:#3794ff; --vscode-errorForeground:#f14c4c; --vscode-list-warningForeground:#cca700;
    --vscode-widget-border:#3c3c3c; --vscode-focusBorder:#0078d4;
  }
  body { margin:0; width:${width}px; }
  #shot { width:${width}px; }
</style></head><body><div id="shot">${bodyHtml}</div></body></html>`;
}

function fleetAgents(): AgentVM[] {
  const fixture = sidebarFixtures["internal-plan-line"];
  const vm = fixture.vm as FleetVM;
  return vm.agents;
}

describe("t-281339 — plan line at two widths", () => {
  let browser: Browser;
  let page: Page;
  let AgentRow: (props: unknown) => unknown;
  const written: string[] = [];

  beforeAll(async () => {
    mkdirSync(OUT_DIR, { recursive: true });
    const mod = await loadWebviewModule(path.resolve(__dirname, "../../packages/webview-ui/src/webview/sidebar/App.tsx"));
    AgentRow = mod.AgentRow as typeof AgentRow;
    browser = await puppeteer.launch({ executablePath: resolveChromeExecutable(), headless: true });
    page = await browser.newPage();
  }, 60_000);

  afterAll(async () => {
    await browser?.close();
    if (written.length) {
      writeFileSync(
        path.join(OUT_DIR, "README.md"),
        `# t-281339 — sidebar plan line\n\nFour agents, two widths. Regenerated by \`test/browser/sidebarPlanLineShots.test.ts\`.\n\n${written.map((f) => `- \`${f}\``).join("\n")}\n`,
        "utf8",
      );
    }
  });

  function rowsHtml(): string {
    return fleetAgents().map((a) => renderStatic(AgentRow({ a, flash: false }))).join("");
  }

  it("clips a long step at 360 and does not grow the card; shots both widths", async () => {
    for (const w of WIDTHS) {
      await page.setViewport({ width: w.px + 40, height: 900, deviceScaleFactor: 2 });
      await page.setContent(pageHtml(rowsHtml(), w.px), { waitUntil: "load" });
      const file = path.join(OUT_DIR, `internal-plan-line-${w.id}.png`);
      const target = await page.$("#shot");
      await target!.screenshot({ path: file as `${string}.png` });
      expect(statSync(file).size, `${file} is empty`).toBeGreaterThan(1000);
      written.push(path.basename(file));

      const measure = await page.evaluate(() => {
        const shot = document.getElementById("shot")!;
        const rows = [...shot.querySelectorAll(".row")].map((row) => ({
          name: (row as HTMLElement).dataset.name,
          width: (row as HTMLElement).getBoundingClientRect().width,
          overflow: (row as HTMLElement).scrollWidth - (row as HTMLElement).clientWidth,
        }));
        const step = shot.querySelector('[data-plan="step"] .plan-text') as HTMLElement | null;
        const mark = shot.querySelector('[data-plan="sem-plano"]') as HTMLElement | null;
        const canal = [...shot.querySelectorAll("*")].some((el) => (el.textContent ?? "").includes("sem-canal"));
        return {
          shotWidth: shot.getBoundingClientRect().width,
          rows,
          step: step ? {
            text: step.textContent,
            overflow: step.scrollWidth - step.clientWidth,
            nowrap: getComputedStyle(step).whiteSpace,
          } : null,
          semPlanoColor: mark ? getComputedStyle(mark.querySelector(".plan-mark")!).color : null,
          warn: getComputedStyle(document.documentElement).getPropertyValue("--ds-warn").trim(),
          paintedCanal: canal,
        };
      });

      expect(measure.paintedCanal).toBe(false);
      expect(measure.step).not.toBeNull();
      expect(measure.semPlanoColor).toBeTruthy();
      if (w.px === 360) {
        expect(measure.shotWidth).toBeLessThanOrEqual(360);
        expect(measure.rows.every((row) => row.width <= 360)).toBe(true);
        expect(measure.step!.nowrap).toBe("nowrap");
        expect(measure.step!.overflow).toBeGreaterThan(0);
      }
    }
  }, 60_000);
});
